// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc981.Competion2016.subsystems;

import java.beans.Encoder;

import org.usfirst.frc981.Competion2016.RobotMap;
import org.usfirst.frc981.Competion2016.commands.*;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrainSubSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final int unused = 0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final AnalogInput analogInputOfPresssureSensor = RobotMap.driveTrainSubSystemAnalogInputOfPresssureSensor;
    private final CANTalon canTalon3 = RobotMap.driveTrainSubSystemCanTalon3;
    private final CANTalon canTalon4 = RobotMap.driveTrainSubSystemCanTalon4;
    private final CANTalon canTalon2 = RobotMap.driveTrainSubSystemCanTalon2;
    private final CANTalon canTalon5 = RobotMap.driveTrainSubSystemCanTalon5;
    private final RobotDrive robotDrive = RobotMap.driveTrainSubSystemRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoysticks());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void getJoystickInputs (Joystick leftJoystick, Joystick rightJoystick) {
    	robotDrive.tankDrive(leftJoystick, rightJoystick);
    }
    
    public void stop () {
    	robotDrive.drive(0.0, 0.0);
    }
}

