// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc981.Competion2016.subsystems;

import org.usfirst.frc981.Competion2016.RobotMap;
import org.usfirst.frc981.Competion2016.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ShooterSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double SPEED_FOR_GRABBING = 0.5;
    public static final double SPEED_FOR_SHOOTING = 1.0;
    public static final double SPEED_TO_KICK = 0.25;
    public static final double SPEED_TO_RETRACT_KICKER = -0.25;
    public static final int AXIS_ID = 1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController kickerController = RobotMap.shooterSubsystemKickerController;
    private final CANTalon canTalonForTilt = RobotMap.shooterSubsystemCanTalonForTilt;
    private final SpeedController leftFlywheelController = RobotMap.shooterSubsystemLeftFlywheelController;
    private final SpeedController rightFlywheelController = RobotMap.shooterSubsystemRightFlywheelController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new StopFlywheelMotors());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setFlywheelSpeed (double flywheelSpeed) {
    	if (flywheelSpeed < -1.0) {
    		flywheelSpeed = -1.0;
    	}
    	if (flywheelSpeed > 1.0) {
    		flywheelSpeed = 1.0;
    	}
    	leftFlywheelController.set(flywheelSpeed);
    	rightFlywheelController.set(flywheelSpeed);
    }
    
    public void stopFlywheels () {
    	leftFlywheelController.stopMotor();
    	rightFlywheelController.stopMotor();
    }
    
    public void kickBall () {
    	kickerController.set(SPEED_TO_KICK);
    }
    
    public void retractKicer() {
    	kickerController.set(SPEED_TO_RETRACT_KICKER);
    }
    
    public void setTiltMotorSpeed (double tiltMotorSpeed) {
    	canTalonForTilt.set(tiltMotorSpeed);
    }
    
    public void stopTiltMotor () {
    	canTalonForTilt.set(0.0);
    }
 }


