// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc982.SnoBotics2017V2.subsystems;

import org.usfirst.frc982.SnoBotics2017V2.RobotMap;
import org.usfirst.frc982.SnoBotics2017V2.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class FuelDumper extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid fuelDumperDoubleSolenoid = RobotMap.fuelDumperFuelDumperDoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
 
        // setDefaultCommand(new ReturnFuelDumper());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    

    
    DoubleSolenoid.Value fuelDumperSolenoid = DoubleSolenoid.Value.kOff;
    
    public void dumpFuel () {
    	fuelDumperDoubleSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void resetDumper () {
    	fuelDumperDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    

    public boolean isFuelDumped () {
    	return (fuelDumperDoubleSolenoid.get() == DoubleSolenoid.Value.kForward);
    }
    
    public boolean isDumperReset() {
    	return (fuelDumperDoubleSolenoid.get() == DoubleSolenoid.Value.kReverse);
    }
    
}

