// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc982.SnoBotics2017V2.subsystems;

import org.usfirst.frc982.SnoBotics2017V2.RobotMap;
import org.usfirst.frc982.SnoBotics2017V2.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearManipulator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid paddleSolenoid = RobotMap.gearManipulatorPaddleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new CloseGearPaddles());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    DoubleSolenoid.Value paddleState = DoubleSolenoid.Value.kOff;

    public void openPaddles () {
    	paddleSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void closePaddles () {
    	paddleSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public boolean isPaddleOpen () {
    	return true;
    	/*
    	leftPaddleState = leftPaddleSolenoid.get();
    	rightPaddleState = rightPaddleSolenoid.get();
    	
    	if ((leftPaddleState == DoubleSolenoid.Value.kForward) &&
    			(rightPaddleState == DoubleSolenoid.Value.kForward)) {
    		return true;
    	} else {
    		return false;
    	}
    	*/
    }
    
    public boolean isPaddleClosed () {
    	return true;
    	/*
    	leftPaddleState = leftPaddleSolenoid.get();
    	rightPaddleState = rightPaddleSolenoid.get();
    	
    	if ((leftPaddleState == DoubleSolenoid.Value.kReverse) &&
    			(rightPaddleState == DoubleSolenoid.Value.kReverse)) {
    		return true;
    	} else {
    		return false;
    	}
    	*/
    }
    	
}
